In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
from scipy.stats import f_oneway

In [3]:
df= sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [18]:
df=df[['age','pclass']].dropna()
df

      age  pclass
0    22.0       3
1    38.0       1
2    26.0       3
3    35.0       1
4    35.0       3
..    ...     ...
885  39.0       3
886  27.0       2
887  19.0       1
889  26.0       1
890  32.0       3

[714 rows x 2 columns]

In [19]:
df['pclass'].unique()

array([3, 1, 2])

In [20]:
class1 =df[df['pclass']==1]['age']
class2 =df[df['pclass']==2]['age']
class3 =df[df['pclass']==3]['age']
class1

1      38.0
3      35.0
6      54.0
11     58.0
23     28.0
       ...
871    47.0
872    33.0
879    56.0
887    19.0
889    26.0
Name: age, Length: 186, dtype: float64

In [26]:
h0 = " there is no differnce between the passenger class and ages"
h1 ="there is a differnce  between the passenger class and ages "
h0,h1

(' there is no differnce between the passenger class and ages',
 'there is a differnce  between the passenger class and ages ')

In [22]:
f_stats, p_value = f_oneway(class1,class2,class3)

In [23]:
f_stats

np.float64(57.44348434067624)

In [24]:
p_value

np.float64(7.487984171957403e-24)

In [27]:
alpha = 0.05 
if p_value<alpha :
    print(h1)
else:
    print(h0)

there is a differnce  between the passenger class and ages